export const STORAGE_PROJECT_ID = ":SELECTED_PROJECT_ID";

export const SETTINGS_REMEMBER_PROJECT = ":REMEMBER_PROJECT";
export const SETTINGS_PROJECT_ID = STORAGE_PROJECT_ID;
export const SETTINGS_THEME = ":THEME";

export const TASK_INCOMPLETE = "INCOMPLETE";
export const TASK_COMPLETED = "COMPLETED";
export const TASK_STATES = [TASK_INCOMPLETE, TASK_COMPLETED, null];
